sudo: required
dist: trusty
language: python
python:
  - '3.5'
ruby:
  - '2.2.3'
services:
  - postgresql
before_script:
  - psql -c 'create database notes_test;' -U postgres
install: pip install --use-wheel -r requirements.txt
script: python manage.py build_and_test
env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - BOTO_CONFIG=/tmp/nowhere
    - TRAVIS_CI=True
