sudo: required
dist: trusty
language: python
python:
  - '3.5'
ruby:
  - '2.2.3'
install: pip install -r requirements.txt
script: python manage.py build_and_test
env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - BOTO_CONFIG=/tmp/nowhere
    - TRAVIS_CI=True
